### ISSUE TITLE
MMQTTException: Connection Refused - Unauthorized

### ISSUE THREAD

**Issue by MartinJoeWilco** [adafruit/Adafruit_CircuitPython_AzureIoT#47]
Hello all,

Seeking some guidance with a  Connection Refused - Unauthorized error.
On the Azure side all is configured to allow external IoT access 

Im using a Adafruit ESP32-S2 TFT Feather, where the internet connection works accordingly.
Any thoughts? Below is the output when trying to connect.

Regards

```
16946.477: DEBUG - Hostname: _{removedurl}_.azure-devices.net
16946.484: DEBUG - Device Id: _{removed device ID}_
16946.492: DEBUG - Shared Access Key: _{removed the key}_
16947.132: INFO - - iot_mqtt :: connect :: _{removedurl}_.azure-devices.net
16947.141: DEBUG - - iot_mqtt :: _on_connect :: username = _{removed details}_
16947.141: DEBUG - Attempting to establish MQTT connection...
16947.148: INFO - Establishing a SECURE SSL connection to _{removedurl}_.azure-devices.net:8883
16948.843: DEBUG - Sending CONNECT to broker...
16948.843: DEBUG - Fixed Header: bytearray(b'\x10\xca\x01\x00')
Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00x')
16948.944: DEBUG - Receiving CONNACK packet from broker
Traceback (most recent call last):
  File "code.py", line 97, in <module>
  File "adafruit_azureiot/iothub_device.py", line 309, in connect
  File "adafruit_azureiot/iot_mqtt.py", line 390, in connect
  File "adafruit_azureiot/iot_mqtt.py", line 149, in _create_mqtt_client
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 523, in connect
MMQTTException: Connection Refused - Unauthorized
```

**Comment by MartinJoeWilco** [comment]
Realize I didn't post the code. 

```
import time
import board
import busio
import ssl
import wifi
import socketpool
import displayio
import adafruit_requests
import ipaddress
import gc
from adafruit_azureiot import IoTHubDevice

import adafruit_gps
from adafruit_lc709203f import LC709203F, PackSize
import microcontroller


try:
    from secrets import secrets
except ImportError:
        print("Ploppers! An error occurred getting the WiFi details")
        raise


print("Connecting to the WiFi %s"%secrets["ssid"])
try:
    wifi.radio.connect(secrets["ssid"], secrets["password"])
except:
    print("Ploppers! Couldn't connect to %s"%secrets["ssid"])

else:
    print("Connected to %s!"%secrets["ssid"])

pool = socketpool.SocketPool(wifi.radio)
esp = None
device = IoTHubDevice(pool, esp, secrets["device_connection_string"])  
device.connect()

```

**Comment by brentru** [comment]
Are you able to try running the [simple test](https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/blob/main/examples/azureiot_native_networking/azureiot_hub_simpletest.py) on this device?

**Comment by MartinJoeWilco** [comment]
Hi Brentru,

The simple test did not worked (for me) on the Adafruit ESP32-S2 TFT Feather [device link](https://learn.adafruit.com/adafruit-esp32-s2-tft-feather)

When using the code, for line 32: `spi = busio.SPI(board.SCK, board.MOSI, board.MISO)`
I get the following error: "ValueError: SCK in use"

Hence I approached the wifi connection in a different matter (see my code example in my second post above).
Where I set `esp = None` as IoTHubDevice() with two arguments (see example code from GitHub below) raises an error: "TypeError: function takes 4 positional arguments but 3 were given"

```
from adafruit_azureiot import IoTHubDevice
device = IoTHubDevice(wifi, secrets["device_connection_string"])
device.connect()
```

**Comment by BlitzCityDIY** [comment]
i have been doing some Azure IoT stuff with the Feather ESP32-S2 TFT. I haven't encountered that error but I am using the IoT Central configuration rather than IoT Hub. Are you using the native WIFI example? The ESP32-S2 feather does not use ESP SPI for connection. I modified my code to basically be a simple connection test for `IoTCentralDevice` and am including it below. I've built it on the `simpletest` for native WIFI: https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/blob/main/examples/azureiot_native_networking/azureiot_central_simpletest.py

so if you're using Hub, you'll want to build on this one: https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/blob/main/examples/azureiot_native_networking/azureiot_hub_simpletest.py
```
# SPDX-FileCopyrightText: 2022 Liz Clark for Adafruit Industries
# SPDX-License-Identifier: MIT

import json
import simpleio
import time
import board
import terminalio
import rtc
import socketpool
import wifi
import adafruit_ntp
from adafruit_azureiot import IoTCentralDevice

# Get wifi details and more from a secrets.py file
try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise

print("Connecting to WiFi...")
wifi.radio.connect(secrets["ssid"], secrets["password"])

print("Connected to WiFi!")

if time.localtime().tm_year < 2022:
    print("Setting System Time in UTC")
	pool = socketpool.SocketPool(wifi.radio)
	ntp = adafruit_ntp.NTP(pool, tz_offset=-4)
    # NOTE: This changes the system time so make sure you aren't assuming that time
    # doesn't jump.
    rtc.RTC().datetime = ntp.datetime
    
else:
    print("Year seems good, skipping set time.")


# To use Azure IoT Central, you will need to create an IoT Central app.
# You can either create a free tier app that will live for 7 days without an Azure subscription,
# Or a standard tier app that will last for ever with an Azure subscription.
# The standard tiers are free for up to 2 devices
#
# If you don't have an Azure subscription:
#
# If you are a student, head to https://aka.ms/FreeStudentAzure and sign up, validating with your
#  student email address. This will give you $100 of Azure credit and free tiers of a load of
#  service, renewable each year you are a student
#
# If you are not a student, head to https://aka.ms/FreeAz and sign up to get $200 of credit for 30
#  days, as well as free tiers of a load of services
#
# Create an Azure IoT Central app by following these instructions: https://aka.ms/CreateIoTCentralApp
# Add a device template with telemetry, properties and commands, as well as a view to visualize the
# telemetry and execute commands, and a form to set properties.
#
# Next create a device using the device template, and select Connect to get the device connection details.
# Add the connection details to your secrets.py file, using the following values:
#
# 'id_scope' - the devices ID scope
# 'device_id' - the devices device id
# 'device_sas_key' - the devices primary key
#
# The adafruit-circuitpython-azureiot library depends on the following libraries:
#
# From the Adafruit CircuitPython Bundle (https://github.com/adafruit/Adafruit_CircuitPython_Bundle):
# * adafruit-circuitpython-minimqtt
# * adafruit-circuitpython-requests

# Create an IoT Hub device client and connect
esp = None
pool = socketpool.SocketPool(wifi.radio)
device = IoTCentralDevice(
    pool, esp, secrets["id_scope"], secrets["device_id"], secrets["device_sas_key"]
)

print("Connecting to Azure IoT Central...")
device.connect()

print("Connected to Azure IoT Central!")

azure_clock = time.monotonic()

while True:
    try:

        # Send telemetry every minute
        # You can see the values in the devices dashboard
        if (time.monotonic() - azure_clock) > 900:
            message = {"Temperature": 75,
                       "Humidity": 50}
            device.send_telemetry(json.dumps(message))
            azure_clock = time.monotonic()

        # Poll every second for messages from the cloud
        device.loop()
    except (ValueError, RuntimeError) as e:
        print("Connection error, reconnecting\n", str(e))
        wifi.radio.enabled = False
        wifi.radio.enabled = True
        wifi.radio.connect(secrets["ssid"], secrets["password"])
        device.reconnect()
        continue```
